### PR TITLE
6-Remove sqlite and add postgresql

### PR DESCRIPTION
**Pull request by godfreym**
Issue #6 

### Note:
This PR removes `sqlite` and add the `postgresql` since we use the later and not `sqlite`

### CODE REVIEW

**Comment by godfreym** [comment]
@leonardk1 Please Review

**Comment by leonardk1** [comment]
@godfreym thats is cool
:+1:

**Comment by leonardk1** [comment]
@godfreym you also need to create a database user for the dev and test environments

**Comment by godfreym** [comment]
@leonardk1 please read the PR title and you will notice that your last comment should be on the issue and not in this PR

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by leonardk1** [comment]
:+1:

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by arafatm** [comment]
:+1:

**Pull request merged**
