### PR TITLE
10-User interface integration

### PR DESCRIPTION
**Pull request by godfreym**
Issue #10 

### Story:
AS AN Admin I WANT To be able to access the application SO THAT I can upload the campaigns

### Acceptance Criteria:
- [x] GIVEN I am the admin accessing the application via a web browser THEN I should be able to access the form for uploading the campaigns

### CODE REVIEW

**Comment by godfreym** [comment]
@leonardk1 Please Review

**Comment by leonardk1** [comment]
@godfreym looks good
let me check out the real view on my machine

**Comment by godfreym** [comment]
@arafatm Please Review

**Comment by leonardk1** [comment]
@godfreym the view is ok

**Comment by arafatm** [comment]
:+1:

**Pull request merged**
