### PR TITLE
4 send questions to participants

### PR DESCRIPTION
**Pull request by leonardk1**
As an Admin
I Want To Send Questions To Participants
So That I Can Get Feed Back From them concerning the campaigns

##### Tasks
- [x] Send Initial Question to participants
- [ ] Get Feed Back From the Participants and send them the next set of questions

### CODE REVIEW

**Comment by leonardk1** [comment]
@arafatm this is the PR that needs to be reviewed

**Comment by arafatm** [comment]
@godfreym have you reviewed this?

**Comment by arafatm** [comment]
:+1:

**Comment by godfreym** [comment]
@leonardk1 The code looks fine, though the second task from the main PR list of tasks should be cleared I hope it will be taken care in the next PR, right @leonardk1 ?

**Pull request merged**
