### PR TITLE
15 rename models

### PR DESCRIPTION
**Pull request by leonardk1**
#15
As A  Developer
I Want To rename the participant_answer Model to answer model
To Make it more easier to relate with for all the developers

##### Tasks
- [x] rename related files and make appropriate rails migrations

### CODE REVIEW

**Comment by leonardk1** [comment]
@godfreym please review

**Comment by godfreym** [comment]
@leonardk1 how about seed files, did you rename them too?

**Comment by leonardk1** [comment]
@godfreym there was no seed file for that model
@arafatm please review

**Comment by leonardk1** [comment]
@arafatm this has been fixed now

**Comment by arafatm** [comment]
merge it

**Pull request merged**
